{
 "title": "YazLab II - Dispatcher Observability",
 "tags": [
  "dispatcher",
  "observability"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Traffic (Req/s)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{endpoint}} - {{status}}" }
   ]
  },
  {
   "title": "Global Latency (p95 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Live Dispatcher Logs (Structured)",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"dispatcher\"} | json"
    }
   ]
  }
 ]
}